/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root_api__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/db": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Db */
        get: operations["health_db_api_health_db_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Users
         * @description Admin only. For the trainer picker when creating a training.
         */
        get: operations["list_users_api_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trainings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Trainings
         * @description Employees: upcoming, not cancelled trainings for their own level, soonest first.
         *     Admins: every training (past and cancelled too), optionally filtered by level.
         */
        get: operations["list_trainings_api_trainings_get"];
        put?: never;
        /**
         * Create Training
         * @description Admin only. Times must be sent in UTC (or with an offset); they come back in UTC.
         */
        post: operations["create_training_api_trainings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trainings/{training_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Training */
        get: operations["get_training_api_trainings__training_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Client
         * @description The client a user works for. Also used for seat zones.
         * @enum {string}
         */
        Client: "DKB" | "Deka" | "VV" | "DBIS" | "UNION";
        /**
         * CurrentUserRead
         * @description GET /api/auth/me. No password_hash: if it's not in the schema, it can't leak.
         */
        CurrentUserRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Email */
            email: string;
            client: components["schemas"]["Client"];
            level: components["schemas"]["Level"];
            /** Is Admin */
            is_admin: boolean;
            /** Is Team Lead */
            is_team_lead: boolean;
            team_lead: components["schemas"]["TeamLeadSummary"] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Level
         * @description Seniority, in order from junior to senior architect.
         * @enum {string}
         */
        Level: "junior" | "expert" | "senior" | "architect" | "senior_architect";
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** TeamLeadSummary */
        TeamLeadSummary: {
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             * @constant
             */
            token_type: "bearer";
        };
        /** TrainerRead */
        TrainerRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /**
         * TrainingCreate
         * @description POST /api/trainings. Every agreed F2 validation rule lives here (FE mirrors them).
         */
        TrainingCreate: {
            /** Name */
            name: string;
            /** Description */
            description: string;
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            /**
             * Ends At
             * Format: date-time
             */
            ends_at: string;
            /** Max Seats */
            max_seats: number;
            /** Trainer Id */
            trainer_id?: number | null;
            /** External Trainer Name */
            external_trainer_name?: string | null;
            /** Levels */
            levels: components["schemas"]["Level"][];
        };
        /** TrainingRead */
        TrainingRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            /**
             * Ends At
             * Format: date-time
             */
            ends_at: string;
            /** Levels */
            levels: components["schemas"]["Level"][];
            trainer: components["schemas"]["TrainerRead"] | null;
            /** External Trainer Name */
            external_trainer_name: string | null;
            /** Max Seats */
            max_seats: number;
            /** Seats Left */
            seats_left: number;
            /** Cancelled */
            cancelled: boolean;
            /** My Enrollment Status */
            my_enrollment_status?: string | null;
            /** Description */
            description: string;
        };
        /**
         * TrainingSummary
         * @description A training in a list. TrainingRead adds the description.
         */
        TrainingSummary: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            /**
             * Ends At
             * Format: date-time
             */
            ends_at: string;
            /** Levels */
            levels: components["schemas"]["Level"][];
            trainer: components["schemas"]["TrainerRead"] | null;
            /** External Trainer Name */
            external_trainer_name: string | null;
            /** Max Seats */
            max_seats: number;
            /** Seats Left */
            seats_left: number;
            /** Cancelled */
            cancelled: boolean;
            /** My Enrollment Status */
            my_enrollment_status?: string | null;
        };
        /**
         * UserSummary
         * @description GET /api/users: just enough to pick someone, e.g. a trainer.
         */
        UserSummary: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Email */
            email: string;
            level: components["schemas"]["Level"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root_api__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_db_api_health_db_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Invalid email or password */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUserRead"];
                };
            };
            /** @description Missing, invalid or expired token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_users_api_users_get: {
        parameters: {
            query?: {
                /** @description Part of a name or email */
                search?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSummary"][];
                };
            };
            /** @description Missing, invalid or expired token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Admins only */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_trainings_api_trainings_get: {
        parameters: {
            query?: {
                /** @description Admins only; ignored for everyone else */
                level?: components["schemas"]["Level"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainingSummary"][];
                };
            };
            /** @description Missing, invalid or expired token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_training_api_trainings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrainingCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainingRead"];
                };
            };
            /** @description Missing, invalid or expired token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Admins only */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_training_api_trainings__training_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                training_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainingRead"];
                };
            };
            /** @description Missing, invalid or expired token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found, or not for your level */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
