/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root_api__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/db": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Db */
        get: operations["health_db_api_health_db_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Users
         * @description Admin only. For the trainer picker when creating a training.
         */
        get: operations["list_users_api_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trainings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Trainings
         * @description Employees: upcoming, not cancelled trainings for their own level, soonest first.
         *     Admins: every training (past and cancelled too), optionally filtered by level.
         */
        get: operations["list_trainings_api_trainings_get"];
        put?: never;
        /**
         * Create Training
         * @description Admin only. Times must be sent in UTC (or with an offset); they come back in UTC.
         *     An unknown trainer_id is a 422 like any other validation error.
         */
        post: operations["create_training_api_trainings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trainings/{training_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Training */
        get: operations["get_training_api_trainings__training_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Training
         * @description Admin only. Send only the fields to change; `null` clears the trainer fields.
         *     409 if the training is cancelled, or max_seats would drop below the approved count.
         */
        patch: operations["update_training_api_trainings__training_id__patch"];
        trace?: never;
    };
    "/api/trainings/{training_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Training
         * @description Admin only. A soft delete: the training stays, marked cancelled.
         *     409 if it's already cancelled or has already started.
         */
        post: operations["cancel_training_api_trainings__training_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/enrollments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * My Enrollments
         * @description My upcoming (approved), pending and completed trainings, for the Profile page.
         */
        get: operations["my_enrollments_api_me_enrollments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trainings/{training_id}/enrollments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request To Join
         * @description Ask for a seat. Creates a pending enrollment for the team lead (or an admin) to decide,
         *     notifies them in the app, and emails them after the response is sent.
         */
        post: operations["request_to_join_api_trainings__training_id__enrollments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/approvals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Approvals
         * @description Pending requests I can decide: my reports', plus (for admins) people without a team lead.
         *     Only upcoming, uncancelled trainings. Oldest request first. Empty for everyone else.
         */
        get: operations["list_approvals_api_approvals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/enrollments/{enrollment_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve
         * @description Approve a pending request if the training still has a seat.
         */
        post: operations["approve_api_enrollments__enrollment_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/enrollments/{enrollment_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reject
         * @description Reject a pending request, optionally with a comment. The user can't ask again.
         */
        post: operations["reject_api_enrollments__enrollment_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/enrollments/{enrollment_id}/withdraw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Withdraw
         * @description Withdraw my own pending or approved enrollment, before the training starts.
         */
        post: operations["withdraw_api_enrollments__enrollment_id__withdraw_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Notifications
         * @description My latest notifications, newest first, and how many are unread. FE polls this every 30 s.
         */
        get: operations["list_notifications_api_notifications_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark All Read */
        post: operations["mark_all_read_api_notifications_read_all_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/{notification_id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark Read */
        post: operations["mark_read_api_notifications__notification_id__read_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/seats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Seat Map
         * @description Every seat's status on a day, sorted by zone, row and column.
         */
        get: operations["seat_map_api_seats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reservations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reserve
         * @description Reserve a seat for a day. If I already have a seat that day, it moves to this one.
         */
        post: operations["reserve_api_reservations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reservations/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * My Reservations
         * @description My reservations from today on, soonest first.
         */
        get: operations["my_reservations_api_reservations_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reservations/{reservation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Cancel */
        delete: operations["cancel_api_reservations__reservation_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Upload Avatar
         * @description Set or replace my profile picture (multipart/form-data, field `file`). Returns me, with the new avatar_url.
         */
        put: operations["upload_avatar_api_me_avatar_put"];
        post?: never;
        /**
         * Delete Avatar
         * @description Remove my profile picture (back to initials).
         */
        delete: operations["delete_avatar_api_me_avatar_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{user_id}/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Avatar
         * @description The picture itself. No login needed, because <img src> can't send a Bearer token.
         *     avatar_url carries a version (?v=…), so the image can be cached for a year.
         */
        get: operations["get_avatar_api_users__user_id__avatar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ApprovalRead
         * @description GET /api/approvals: one pending request with who asked and for what.
         */
        ApprovalRead: {
            enrollment: components["schemas"]["EnrollmentRead"];
            user: components["schemas"]["Requester"];
            training: components["schemas"]["TrainingSummary"];
        };
        /** Body_upload_avatar_api_me_avatar_put */
        Body_upload_avatar_api_me_avatar_put: {
            /**
             * File
             * @description JPEG, PNG or WebP, max 512 KB
             */
            file: string;
        };
        /**
         * Client
         * @description The client a user works for. Also used for seat zones.
         * @enum {string}
         */
        Client: "DKB" | "Deka" | "VV" | "DBIS" | "UNION";
        /**
         * CurrentUserRead
         * @description GET /api/auth/me. No password_hash: if it's not in the schema, it can't leak.
         */
        CurrentUserRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Email */
            email: string;
            client: components["schemas"]["Client"];
            level: components["schemas"]["Level"];
            /** Is Admin */
            is_admin: boolean;
            /** Is Team Lead */
            is_team_lead: boolean;
            team_lead: components["schemas"]["TeamLeadSummary"] | null;
            /** Avatar Url */
            avatar_url: string | null;
        };
        /**
         * DecisionRequest
         * @description Body of approve / reject. The comment is optional and shown to the requester.
         */
        DecisionRequest: {
            /** Comment */
            comment?: string | null;
        };
        /** EnrollmentRead */
        EnrollmentRead: {
            /** Id */
            id: number;
            /** Training Id */
            training_id: number;
            /** User Id */
            user_id: number;
            status: components["schemas"]["EnrollmentStatus"];
            /** Decision Comment */
            decision_comment: string | null;
            /**
             * Requested At
             * Format: date-time
             */
            requested_at: string;
            /** Decided At */
            decided_at: string | null;
        };
        /**
         * EnrollmentStatus
         * @description pending -> approved | rejected; pending | approved -> withdrawn.
         * @enum {string}
         */
        EnrollmentStatus: "pending" | "approved" | "rejected" | "withdrawn";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Level
         * @description Seniority, in order from junior to senior architect.
         * @enum {string}
         */
        Level: "junior" | "expert" | "senior" | "architect" | "senior_architect";
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * MyEnrollments
         * @description GET /api/me/enrollments: the Profile page's three sections.
         */
        MyEnrollments: {
            /** Upcoming */
            upcoming: components["schemas"]["TrainingSummary"][];
            /** Pending */
            pending: components["schemas"]["TrainingSummary"][];
            /** Completed */
            completed: components["schemas"]["TrainingSummary"][];
        };
        /**
         * NotificationList
         * @description GET /api/notifications. unread_count covers all of them, not just the listed ones.
         */
        NotificationList: {
            /** Unread Count */
            unread_count: number;
            /** Items */
            items: components["schemas"]["NotificationRead"][];
        };
        /** NotificationRead */
        NotificationRead: {
            /** Id */
            id: number;
            type: components["schemas"]["NotificationType"];
            /** Message */
            message: string;
            /** Link */
            link: string | null;
            /** Read */
            read: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * NotificationType
         * @description What happened. FE can pick an icon per type; the message is ready to show.
         * @enum {string}
         */
        NotificationType: "enrollment_requested" | "enrollment_approved" | "enrollment_rejected" | "enrollment_withdrawn" | "training_cancelled" | "training_changed";
        /** Occupant */
        Occupant: {
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /** Requester */
        Requester: {
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /** ReservationCreate */
        ReservationCreate: {
            /** Seat Id */
            seat_id: number;
            /**
             * Date
             * Format: date
             */
            date: string;
        };
        /** ReservationRead */
        ReservationRead: {
            /** Id */
            id: number;
            /**
             * Date
             * Format: date
             */
            date: string;
            seat: components["schemas"]["SeatRef"];
        };
        /** SeatRef */
        SeatRef: {
            /** Id */
            id: number;
            /** Label */
            label: string;
            zone: components["schemas"]["Client"];
        };
        /**
         * SeatStatus
         * @description GET /api/seats?date=: one seat on one day.
         */
        SeatStatus: {
            /** Id */
            id: number;
            /** Label */
            label: string;
            zone: components["schemas"]["Client"];
            /** Pos X */
            pos_x: number;
            /** Pos Y */
            pos_y: number;
            /**
             * Status
             * @enum {string}
             */
            status: "free" | "taken" | "mine";
            taken_by: components["schemas"]["Occupant"] | null;
            /** Bookable */
            bookable: boolean;
        };
        /** TeamLeadSummary */
        TeamLeadSummary: {
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             * @constant
             */
            token_type: "bearer";
        };
        /** TrainerRead */
        TrainerRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /**
         * TrainingCreate
         * @description POST /api/trainings. Every agreed F2 validation rule lives here (FE mirrors them).
         */
        TrainingCreate: {
            /** Name */
            name: string;
            /** Description */
            description: string;
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            /**
             * Ends At
             * Format: date-time
             */
            ends_at: string;
            /** Max Seats */
            max_seats: number;
            /** Trainer Id */
            trainer_id?: number | null;
            /** External Trainer Name */
            external_trainer_name?: string | null;
            /** Levels */
            levels: components["schemas"]["Level"][];
        };
        /** TrainingRead */
        TrainingRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            /**
             * Ends At
             * Format: date-time
             */
            ends_at: string;
            /** Levels */
            levels: components["schemas"]["Level"][];
            trainer: components["schemas"]["TrainerRead"] | null;
            /** External Trainer Name */
            external_trainer_name: string | null;
            /** Max Seats */
            max_seats: number;
            /** Seats Left */
            seats_left: number;
            /** Cancelled */
            cancelled: boolean;
            /** My Enrollment Status */
            my_enrollment_status?: string | null;
            /** My Enrollment Id */
            my_enrollment_id?: number | null;
            /** Description */
            description: string;
        };
        /**
         * TrainingSummary
         * @description A training in a list. TrainingRead adds the description.
         */
        TrainingSummary: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            /**
             * Ends At
             * Format: date-time
             */
            ends_at: string;
            /** Levels */
            levels: components["schemas"]["Level"][];
            trainer: components["schemas"]["TrainerRead"] | null;
            /** External Trainer Name */
            external_trainer_name: string | null;
            /** Max Seats */
            max_seats: number;
            /** Seats Left */
            seats_left: number;
            /** Cancelled */
            cancelled: boolean;
            /** My Enrollment Status */
            my_enrollment_status?: string | null;
            /** My Enrollment Id */
            my_enrollment_id?: number | null;
        };
        /**
         * TrainingUpdate
         * @description PATCH /api/trainings/{id}: any subset of TrainingCreate's fields.
         *
         *     Only fields that were sent are applied (model_dump(exclude_unset=True)), so
         *     "field missing" (keep it) and "field: null" (clear it) mean different things.
         *     Rules that involve two fields (end after start, trainer XOR external) are
         *     checked in the service against the training as it will be after the change.
         */
        TrainingUpdate: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Starts At */
            starts_at?: string | null;
            /** Ends At */
            ends_at?: string | null;
            /** Max Seats */
            max_seats?: number | null;
            /** Trainer Id */
            trainer_id?: number | null;
            /** External Trainer Name */
            external_trainer_name?: string | null;
            /** Levels */
            levels?: components["schemas"]["Level"][] | null;
        };
        /**
         * UserSummary
         * @description GET /api/users: just enough to pick someone, e.g. a trainer.
         */
        UserSummary: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Email */
            email: string;
            level: components["schemas"]["Level"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root_api__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_db_api_health_db_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Invalid email or password */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUserRead"];
                };
            };
            /** @description Missing, invalid or expired token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_users_api_users_get: {
        parameters: {
            query?: {
                /** @description Part of a name or email */
                search?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSummary"][];
                };
            };
            /** @description Missing, invalid or expired token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Admins only */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_trainings_api_trainings_get: {
        parameters: {
            query?: {
                /** @description Admins only; ignored for everyone else */
                level?: components["schemas"]["Level"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainingSummary"][];
                };
            };
            /** @description Missing, invalid or expired token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_training_api_trainings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrainingCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainingRead"];
                };
            };
            /** @description Missing, invalid or expired token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Admins only */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_training_api_trainings__training_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                training_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainingRead"];
                };
            };
            /** @description Missing, invalid or expired token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found, or not for your level */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_training_api_trainings__training_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                training_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrainingUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainingRead"];
                };
            };
            /** @description Missing, invalid or expired token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Admins only */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Training not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Business rule, e.g. {"detail": {"code": "training_cancelled", ...}} */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_training_api_trainings__training_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                training_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainingRead"];
                };
            };
            /** @description Missing, invalid or expired token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Admins only */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Training not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Business rule, e.g. {"detail": {"code": "training_cancelled", ...}} */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    my_enrollments_api_me_enrollments_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyEnrollments"];
                };
            };
            /** @description Missing, invalid or expired token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    request_to_join_api_trainings__training_id__enrollments_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                training_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollmentRead"];
                };
            };
            /** @description Missing, invalid or expired token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not for your level */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Training not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description already_requested | request_rejected | training_full | training_started | training_cancelled */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_approvals_api_approvals_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalRead"][];
                };
            };
            /** @description Missing, invalid or expired token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    approve_api_enrollments__enrollment_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                enrollment_id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["DecisionRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollmentRead"];
                };
            };
            /** @description Missing, invalid or expired token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not one of your reports */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Enrollment not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description not_pending | training_full | training_started | training_cancelled */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_api_enrollments__enrollment_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                enrollment_id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["DecisionRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollmentRead"];
                };
            };
            /** @description Missing, invalid or expired token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not one of your reports */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Enrollment not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description not_pending | training_full | training_started | training_cancelled */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    withdraw_api_enrollments__enrollment_id__withdraw_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                enrollment_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollmentRead"];
                };
            };
            /** @description Missing, invalid or expired token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not your enrollment */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Enrollment not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description not_withdrawable | training_started */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_notifications_api_notifications_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationList"];
                };
            };
            /** @description Missing, invalid or expired token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_all_read_api_notifications_read_all_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing, invalid or expired token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    mark_read_api_notifications__notification_id__read_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notification_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing, invalid or expired token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found (or not yours) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    seat_map_api_seats_get: {
        parameters: {
            query: {
                /** @description YYYY-MM-DD */
                date: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeatStatus"][];
                };
            };
            /** @description Missing, invalid or expired token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description date_in_past | date_too_far | date_weekend */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    reserve_api_reservations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReservationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReservationRead"];
                };
            };
            /** @description Missing, invalid or expired token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Another client's zone */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Seat not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description seat_taken (someone was faster) | already_reserved */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description date_in_past | date_too_far | date_weekend */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    my_reservations_api_reservations_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReservationRead"][];
                };
            };
            /** @description Missing, invalid or expired token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    cancel_api_reservations__reservation_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reservation_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing, invalid or expired token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not yours */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Reservation not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description reservation_in_past */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_avatar_api_me_avatar_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_avatar_api_me_avatar_put"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUserRead"];
                };
            };
            /** @description Missing, invalid or expired token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description avatar_type | avatar_too_large | avatar_not_image */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_avatar_api_me_avatar_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing, invalid or expired token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_avatar_api_users__user_id__avatar_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": unknown;
                    "image/png": unknown;
                    "image/webp": unknown;
                };
            };
            /** @description No picture */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
