"""add reminded_at

Revision ID: c627714143c8
Revises: eed7dc24dcf8
Create Date: 2026-09-25 18:31:06.442301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c627714143c8'
down_revision: Union[str, Sequence[str], None] = 'eed7dc24dcf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrollments', sa.Column('reminded_at', sa.DateTime(), nullable=True))
    op.add_column('seat_reservations', sa.Column('reminded_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seat_reservations', 'reminded_at')
    op.drop_column('enrollments', 'reminded_at')
    # ### end Alembic commands ###
