"""create trainings and training_levels

Revision ID: 2630e899b70d
Revises: 81f4375cc670
Create Date: 2026-09-25 14:11:46.581214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2630e899b70d'
down_revision: Union[str, Sequence[str], None] = '81f4375cc670'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trainings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=False),
    sa.Column('max_seats', sa.Integer(), nullable=False),
    sa.Column('trainer_id', sa.Integer(), nullable=True),
    sa.Column('external_trainer_name', sa.String(length=100), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ends_at > starts_at', name=op.f('ck_trainings_ends_after_start')),
    sa.CheckConstraint('max_seats > 0', name=op.f('ck_trainings_max_seats_positive')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_trainings_created_by_users')),
    sa.ForeignKeyConstraint(['trainer_id'], ['users.id'], name=op.f('fk_trainings_trainer_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trainings'))
    )
    op.create_index(op.f('ix_trainings_created_by'), 'trainings', ['created_by'], unique=False)
    op.create_index(op.f('ix_trainings_trainer_id'), 'trainings', ['trainer_id'], unique=False)
    op.create_table('training_levels',
    sa.Column('training_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Enum('junior', 'expert', 'senior', 'architect', 'senior_architect', name='level', native_enum=False, length=32), nullable=False),
    sa.ForeignKeyConstraint(['training_id'], ['trainings.id'], name=op.f('fk_training_levels_training_id_trainings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('training_id', 'level', name=op.f('pk_training_levels'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Edited: no drop_index before drop_table (MySQL error 1553, see the users migration)
    op.drop_table('training_levels')
    op.drop_table('trainings')
