"""create enrollments

Revision ID: 207996da4e9e
Revises: 2630e899b70d
Create Date: 2026-09-25 15:34:20.656542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '207996da4e9e'
down_revision: Union[str, Sequence[str], None] = '2630e899b70d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('training_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'withdrawn', name='enrollmentstatus', native_enum=False, length=32), nullable=False),
    sa.Column('decision_comment', sa.String(length=500), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('decided_by', sa.Integer(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], name=op.f('fk_enrollments_decided_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['training_id'], ['trainings.id'], name=op.f('fk_enrollments_training_id_trainings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_enrollments_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enrollments')),
    sa.UniqueConstraint('training_id', 'user_id', name=op.f('uq_enrollments_training_id'))
    )
    op.create_index(op.f('ix_enrollments_user_id'), 'enrollments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Edited: no drop_index before drop_table (MySQL error 1553, see the users migration)
    op.drop_table('enrollments')
