"""create notifications

Revision ID: 3eb368d6ae41
Revises: 207996da4e9e
Create Date: 2026-09-25 15:54:30.837057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3eb368d6ae41'
down_revision: Union[str, Sequence[str], None] = '207996da4e9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('enrollment_requested', 'enrollment_approved', 'enrollment_rejected', 'enrollment_withdrawn', 'training_cancelled', 'training_changed', name='notificationtype', native_enum=False, length=32), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('link', sa.String(length=200), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index('ix_notifications_user_id_created_at', 'notifications', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Edited: no drop_index before drop_table (MySQL error 1553: the FK on user_id
    # uses this index, see the users migration)
    op.drop_table('notifications')
