"""create training feedback

Revision ID: eed7dc24dcf8
Revises: 134506ab5030
Create Date: 2026-09-25 18:06:15.009625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eed7dc24dcf8'
down_revision: Union[str, Sequence[str], None] = '134506ab5030'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('training_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('comment', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('rating BETWEEN 1 AND 5', name=op.f('ck_training_feedback_rating_1_to_5')),
    sa.ForeignKeyConstraint(['training_id'], ['trainings.id'], name=op.f('fk_training_feedback_training_id_trainings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_training_feedback_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_training_feedback')),
    sa.UniqueConstraint('training_id', 'user_id', name=op.f('uq_training_feedback_training_id'))
    )
    op.create_index(op.f('ix_training_feedback_user_id'), 'training_feedback', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_training_feedback_user_id'), table_name='training_feedback')
    op.drop_table('training_feedback')
    # ### end Alembic commands ###
