"""create users table

Revision ID: 81f4375cc670
Revises: 
Create Date: 2026-09-25 12:35:05.689212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81f4375cc670'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('client', sa.Enum('DKB', 'Deka', 'VV', 'DBIS', 'UNION', name='client', native_enum=False, length=32), nullable=False),
    sa.Column('level', sa.Enum('junior', 'expert', 'senior', 'architect', 'senior_architect', name='level', native_enum=False, length=32), nullable=False),
    sa.Column('is_admin', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('team_lead_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_lead_id'], ['users.id'], name=op.f('fk_users_team_lead_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_index(op.f('ix_users_team_lead_id'), 'users', ['team_lead_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Edited: autogenerate dropped ix_users_team_lead_id first, which MySQL refuses
    # (error 1553: the index is needed by the foreign key). Dropping the table
    # removes its indexes and constraints anyway.
    op.drop_table('users')
