"""create expenses and hr role

Revision ID: 68da4cb8f515
Revises: de14a5706ea5
Create Date: 2026-09-25 19:02:26.785826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '68da4cb8f515'
down_revision: Union[str, Sequence[str], None] = 'de14a5706ea5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('category', sa.Enum('travel', 'accommodation', 'meals', 'training', 'equipment', 'other', name='expensecategory', native_enum=False, length=32), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('spent_on', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('pending_lead', 'pending_hr', 'approved', 'rejected', 'withdrawn', name='expensestatus', native_enum=False, length=32), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('lead_decided_by_id', sa.Integer(), nullable=True),
    sa.Column('lead_decided_at', sa.DateTime(), nullable=True),
    sa.Column('hr_decided_by_id', sa.Integer(), nullable=True),
    sa.Column('hr_decided_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True),
    sa.CheckConstraint('amount > 0', name=op.f('ck_expenses_amount_positive')),
    sa.ForeignKeyConstraint(['hr_decided_by_id'], ['users.id'], name=op.f('fk_expenses_hr_decided_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_decided_by_id'], ['users.id'], name=op.f('fk_expenses_lead_decided_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_expenses_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_expenses'))
    )
    op.create_index(op.f('ix_expenses_status'), 'expenses', ['status'], unique=False)
    op.create_index(op.f('ix_expenses_user_id'), 'expenses', ['user_id'], unique=False)
    op.create_table('expense_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expense_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('data', sa.LargeBinary().with_variant(mysql.MEDIUMBLOB(), 'mysql'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], name=op.f('fk_expense_receipts_expense_id_expenses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_expense_receipts'))
    )
    op.create_index(op.f('ix_expense_receipts_expense_id'), 'expense_receipts', ['expense_id'], unique=False)
    op.add_column('users', sa.Column('is_hr', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_hr')
    op.drop_index(op.f('ix_expense_receipts_expense_id'), table_name='expense_receipts')
    op.drop_table('expense_receipts')
    op.drop_index(op.f('ix_expenses_user_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_status'), table_name='expenses')
    op.drop_table('expenses')
    # ### end Alembic commands ###
