"""create seats

Revision ID: 5a0401f4b237
Revises: 3eb368d6ae41
Create Date: 2026-09-25 16:02:31.905359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a0401f4b237'
down_revision: Union[str, Sequence[str], None] = '3eb368d6ae41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=20), nullable=False),
    sa.Column('zone', sa.Enum('DKB', 'Deka', 'VV', 'DBIS', 'UNION', name='client', native_enum=False, length=32), nullable=False),
    sa.Column('pos_x', sa.Integer(), nullable=False),
    sa.Column('pos_y', sa.Integer(), nullable=False),
    sa.CheckConstraint('pos_x >= 0 AND pos_y >= 0', name=op.f('ck_seats_position_not_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seats')),
    sa.UniqueConstraint('label', name=op.f('uq_seats_label')),
    sa.UniqueConstraint('zone', 'pos_x', 'pos_y', name=op.f('uq_seats_zone'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seats')
    # ### end Alembic commands ###
